// Généré par build_catalogue.py — ne pas éditer à la main.
const SIMULATIONS = [
 {
  "id": "E1AC-01",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L01",
  "lecon_num": 1,
  "type": "paillasse",
  "titre": "Le test de reconnaissance de l'eau",
  "titre_complet": "Paillasse virtuelle — E1AC-01 · le test de reconnaissance de l'eau",
  "fichier": "sims/1AC/L01/enhanced_simulation_E1AC-01.html"
 },
 {
  "id": "E1AC-01",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L01",
  "lecon_num": 1,
  "type": "simulation",
  "titre": "Test de reconnaissance de l'eau",
  "titre_complet": "Simulation — Test de reconnaissance de l'eau",
  "fichier": "sims/1AC/L01/simulation_E1AC-01.html"
 },
 {
  "id": "E1AC-02",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L02",
  "lecon_num": 2,
  "type": "paillasse",
  "titre": "Forme propre et volume propre d'un solide",
  "titre_complet": "Paillasse virtuelle — E1AC-02 · forme propre et volume propre d'un solide",
  "fichier": "sims/1AC/L02/enhanced_simulation_E1AC-02.html"
 },
 {
  "id": "E1AC-02",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L02",
  "lecon_num": 2,
  "type": "simulation",
  "titre": "Les propriétés physiques d'un solide",
  "titre_complet": "Simulation — Les propriétés physiques d'un solide",
  "fichier": "sims/1AC/L02/simulation_E1AC-02.html"
 },
 {
  "id": "E1AC-03",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L02",
  "lecon_num": 2,
  "type": "paillasse",
  "titre": "Volume propre, pas de forme propre",
  "titre_complet": "Paillasse virtuelle — E1AC-03 · volume propre, pas de forme propre",
  "fichier": "sims/1AC/L02/enhanced_simulation_E1AC-03.html"
 },
 {
  "id": "E1AC-04",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L02",
  "lecon_num": 2,
  "type": "paillasse",
  "titre": "Ni forme propre ni volume propre",
  "titre_complet": "Paillasse virtuelle — E1AC-04 · ni forme propre ni volume propre",
  "fichier": "sims/1AC/L02/enhanced_simulation_E1AC-04.html"
 },
 {
  "id": "E1AC-04",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L02",
  "lecon_num": 2,
  "type": "simulation",
  "titre": "Les propriétés physiques d'un gaz",
  "titre_complet": "Simulation — Les propriétés physiques d'un gaz",
  "fichier": "sims/1AC/L02/simulation_E1AC-04.html"
 },
 {
  "id": "E1AC-05",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L03",
  "lecon_num": 3,
  "type": "paillasse",
  "titre": "La division, le ménisque, la hauteur de l'œil",
  "titre_complet": "Paillasse virtuelle — E1AC-05 · la division, le ménisque, la hauteur de l'œil",
  "fichier": "sims/1AC/L03/enhanced_simulation_E1AC-05.html"
 },
 {
  "id": "E1AC-05",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L03",
  "lecon_num": 3,
  "type": "simulation",
  "titre": "Mesure du volume d'un liquide à l'éprouvette graduée",
  "titre_complet": "Simulation — Mesure du volume d'un liquide à l'éprouvette graduée",
  "fichier": "sims/1AC/L03/simulation_E1AC-05.html"
 },
 {
  "id": "E1AC-06",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L03",
  "lecon_num": 3,
  "type": "paillasse",
  "titre": "V = V₂ − V₁, et ce que la différence coûte",
  "titre_complet": "Paillasse virtuelle — E1AC-06 · V = V₂ − V₁, et ce que la différence coûte",
  "fichier": "sims/1AC/L03/enhanced_simulation_E1AC-06.html"
 },
 {
  "id": "E1AC-06",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L03",
  "lecon_num": 3,
  "type": "simulation",
  "titre": "Mesure du volume d'un solide de forme quelconque",
  "titre_complet": "Simulation — Mesure du volume d'un solide de forme quelconque",
  "fichier": "sims/1AC/L03/simulation_E1AC-06.html"
 },
 {
  "id": "E1AC-07",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L04",
  "lecon_num": 4,
  "type": "paillasse",
  "titre": "La masse d'un solide",
  "titre_complet": "Paillasse virtuelle — E1AC-07 · La masse d'un solide",
  "fichier": "sims/1AC/L04/enhanced_simulation_E1AC-07.html"
 },
 {
  "id": "E1AC-07",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L04",
  "lecon_num": 4,
  "type": "simulation",
  "titre": "Mesure de la masse d'un solide",
  "titre_complet": "Simulation — Mesure de la masse d'un solide",
  "fichier": "sims/1AC/L04/simulation_E1AC-07.html"
 },
 {
  "id": "E1AC-08",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L04",
  "lecon_num": 4,
  "type": "paillasse",
  "titre": "La masse d'un liquide",
  "titre_complet": "Paillasse virtuelle — E1AC-08 · La masse d'un liquide",
  "fichier": "sims/1AC/L04/enhanced_simulation_E1AC-08.html"
 },
 {
  "id": "E1AC-08",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L04",
  "lecon_num": 4,
  "type": "simulation",
  "titre": "Mesure de la masse d'un liquide",
  "titre_complet": "Simulation — Mesure de la masse d'un liquide",
  "fichier": "sims/1AC/L04/simulation_E1AC-08.html"
 },
 {
  "id": "E1AC-09",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L05",
  "lecon_num": 5,
  "type": "paillasse",
  "titre": "La masse volumique d'un liquide",
  "titre_complet": "Paillasse virtuelle — E1AC-09 · La masse volumique d'un liquide",
  "fichier": "sims/1AC/L05/enhanced_simulation_E1AC-09.html"
 },
 {
  "id": "E1AC-09",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L05",
  "lecon_num": 5,
  "type": "simulation",
  "titre": "La masse volumique d'un liquide",
  "titre_complet": "Simulation — La masse volumique d'un liquide",
  "fichier": "sims/1AC/L05/simulation_E1AC-09.html"
 },
 {
  "id": "E1AC-10",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L05",
  "lecon_num": 5,
  "type": "paillasse",
  "titre": "La masse volumique d'un solide",
  "titre_complet": "Paillasse virtuelle — E1AC-10 · La masse volumique d'un solide",
  "fichier": "sims/1AC/L05/enhanced_simulation_E1AC-10.html"
 },
 {
  "id": "E1AC-10",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L05",
  "lecon_num": 5,
  "type": "simulation",
  "titre": "La masse volumique d'un solide et l'identification d'un matériau",
  "titre_complet": "Simulation — La masse volumique d'un solide et l'identification d'un matériau",
  "fichier": "sims/1AC/L05/simulation_E1AC-10.html"
 },
 {
  "id": "E1AC-11",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L06",
  "lecon_num": 6,
  "type": "paillasse",
  "titre": "Compression et detente d'un gaz",
  "titre_complet": "Paillasse virtuelle — E1AC-11 · Compression et detente d'un gaz",
  "fichier": "sims/1AC/L06/enhanced_simulation_E1AC-11.html"
 },
 {
  "id": "E1AC-11",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L06",
  "lecon_num": 6,
  "type": "simulation",
  "titre": "Compression et détente d'un gaz — la notion de pression",
  "titre_complet": "Simulation — Compression et détente d'un gaz — la notion de pression",
  "fichier": "sims/1AC/L06/simulation_E1AC-11.html"
 },
 {
  "id": "E1AC-12",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L06",
  "lecon_num": 6,
  "type": "paillasse",
  "titre": "La pression atmospherique",
  "titre_complet": "Paillasse virtuelle — E1AC-12 · La pression atmospherique",
  "fichier": "sims/1AC/L06/enhanced_simulation_E1AC-12.html"
 },
 {
  "id": "E1AC-12",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L06",
  "lecon_num": 6,
  "type": "simulation",
  "titre": "Mise en évidence de la pression atmosphérique",
  "titre_complet": "Simulation — Mise en évidence de la pression atmosphérique",
  "fichier": "sims/1AC/L06/simulation_E1AC-12.html"
 },
 {
  "id": "E1AC-13",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L07",
  "lecon_num": 7,
  "type": "paillasse",
  "titre": "Paillasse virtuelle — E1AC-13",
  "titre_complet": "Paillasse virtuelle — E1AC-13",
  "fichier": "sims/1AC/L07/enhanced_simulation_E1AC-13.html"
 },
 {
  "id": "E1AC-13",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L07",
  "lecon_num": 7,
  "type": "simulation",
  "titre": "Modélisation des trois états de la matière",
  "titre_complet": "Simulation — Modélisation des trois états de la matière",
  "fichier": "sims/1AC/L07/simulation_E1AC-13.html"
 },
 {
  "id": "E1AC-14",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L08",
  "lecon_num": 8,
  "type": "paillasse",
  "titre": "Paillasse virtuelle — E1AC-14",
  "titre_complet": "Paillasse virtuelle — E1AC-14",
  "fichier": "sims/1AC/L08/enhanced_simulation_E1AC-14.html"
 },
 {
  "id": "E1AC-14",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L08",
  "lecon_num": 8,
  "type": "simulation",
  "titre": "Le toucher trompe — mesurer une température au thermomètre",
  "titre_complet": "Simulation — Le toucher trompe — mesurer une température au thermomètre",
  "fichier": "sims/1AC/L08/simulation_E1AC-14.html"
 },
 {
  "id": "E1AC-15",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L08",
  "lecon_num": 8,
  "type": "paillasse",
  "titre": "Paillasse virtuelle — E1AC-15",
  "titre_complet": "Paillasse virtuelle — E1AC-15",
  "fichier": "sims/1AC/L08/enhanced_simulation_E1AC-15.html"
 },
 {
  "id": "E1AC-15",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L08",
  "lecon_num": 8,
  "type": "simulation",
  "titre": "Chaleur et variation de température",
  "titre_complet": "Simulation — Chaleur et variation de température",
  "fichier": "sims/1AC/L08/simulation_E1AC-15.html"
 },
 {
  "id": "E1AC-16",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L09",
  "lecon_num": 9,
  "type": "paillasse",
  "titre": "Paillasse virtuelle — E1AC-16",
  "titre_complet": "Paillasse virtuelle — E1AC-16",
  "fichier": "sims/1AC/L09/enhanced_simulation_E1AC-16.html"
 },
 {
  "id": "E1AC-16",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L09",
  "lecon_num": 9,
  "type": "simulation",
  "titre": "La fusion de la glace — conservation de la masse",
  "titre_complet": "Simulation — La fusion de la glace — conservation de la masse",
  "fichier": "sims/1AC/L09/simulation_E1AC-16.html"
 },
 {
  "id": "E1AC-17",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L09",
  "lecon_num": 9,
  "type": "paillasse",
  "titre": "Paillasse virtuelle — E1AC-17",
  "titre_complet": "Paillasse virtuelle — E1AC-17",
  "fichier": "sims/1AC/L09/enhanced_simulation_E1AC-17.html"
 },
 {
  "id": "E1AC-17",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L09",
  "lecon_num": 9,
  "type": "simulation",
  "titre": "La solidification de l'eau — non-conservation du volume",
  "titre_complet": "Simulation — La solidification de l'eau — non-conservation du volume",
  "fichier": "sims/1AC/L09/simulation_E1AC-17.html"
 },
 {
  "id": "E1AC-22",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L10",
  "lecon_num": 10,
  "type": "paillasse",
  "titre": "Le changement d'état modélisé",
  "titre_complet": "Paillasse virtuelle — E1AC-22 · Le changement d'état modélisé",
  "fichier": "sims/1AC/L10/enhanced_simulation_E1AC-22.html"
 },
 {
  "id": "E1AC-22",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L10",
  "lecon_num": 10,
  "type": "simulation",
  "titre": "Modélisation d'un changement d'état — que devient chaque particule ?",
  "titre_complet": "Simulation — Modélisation d'un changement d'état — que devient chaque particule ?",
  "fichier": "sims/1AC/L10/simulation_E1AC-22.html"
 },
 {
  "id": "E1AC-23",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L11",
  "lecon_num": 11,
  "type": "paillasse",
  "titre": "Homogène ou hétérogène ?",
  "titre_complet": "Paillasse virtuelle — E1AC-23 · Homogène ou hétérogène ?",
  "fichier": "sims/1AC/L11/enhanced_simulation_E1AC-23.html"
 },
 {
  "id": "E1AC-23",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L11",
  "lecon_num": 11,
  "type": "simulation",
  "titre": "Un solide et un liquide : quand distingue-t-on encore les constituants ?",
  "titre_complet": "Simulation — Un solide et un liquide : quand distingue-t-on encore les constituants ?",
  "fichier": "sims/1AC/L11/simulation_E1AC-23.html"
 },
 {
  "id": "E1AC-24",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L11",
  "lecon_num": 11,
  "type": "paillasse",
  "titre": "Miscibles ou non miscibles ?",
  "titre_complet": "Paillasse virtuelle — E1AC-24 · Miscibles ou non miscibles ?",
  "fichier": "sims/1AC/L11/enhanced_simulation_E1AC-24.html"
 },
 {
  "id": "E1AC-24",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L11",
  "lecon_num": 11,
  "type": "simulation",
  "titre": "Deux liquides se mélangent-ils toujours ?",
  "titre_complet": "Simulation — Deux liquides se mélangent-ils toujours ?",
  "fichier": "sims/1AC/L11/simulation_E1AC-24.html"
 },
 {
  "id": "E1AC-18",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L12",
  "lecon_num": 12,
  "type": "paillasse",
  "titre": "Soluble ou insoluble ?",
  "titre_complet": "Paillasse virtuelle — E1AC-18 · Soluble ou insoluble ?",
  "fichier": "sims/1AC/L12/enhanced_simulation_E1AC-18.html"
 },
 {
  "id": "E1AC-18",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L12",
  "lecon_num": 12,
  "type": "simulation",
  "titre": "Dissolution de solides dans l'eau : soluble ou insoluble ?",
  "titre_complet": "Simulation — Dissolution de solides dans l'eau : soluble ou insoluble ?",
  "fichier": "sims/1AC/L12/simulation_E1AC-18.html"
 },
 {
  "id": "E1AC-19",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L12",
  "lecon_num": 12,
  "type": "paillasse",
  "titre": "Jusqu'où peut-on dissoudre ?",
  "titre_complet": "Paillasse virtuelle — E1AC-19 · Jusqu'où peut-on dissoudre ?",
  "fichier": "sims/1AC/L12/enhanced_simulation_E1AC-19.html"
 },
 {
  "id": "E1AC-19",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L12",
  "lecon_num": 12,
  "type": "simulation",
  "titre": "Jusqu'où peut-on dissoudre du sel dans l'eau ?",
  "titre_complet": "Simulation — Jusqu'où peut-on dissoudre du sel dans l'eau ?",
  "fichier": "sims/1AC/L12/simulation_E1AC-19.html"
 },
 {
  "id": "E1AC-20",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L13",
  "lecon_num": 13,
  "type": "paillasse",
  "titre": "La decantation",
  "titre_complet": "Paillasse virtuelle — E1AC-20 · La decantation",
  "fichier": "sims/1AC/L13/enhanced_simulation_E1AC-20.html"
 },
 {
  "id": "E1AC-20",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L13",
  "lecon_num": 13,
  "type": "simulation",
  "titre": "Séparer une eau boueuse par décantation",
  "titre_complet": "Simulation — Séparer une eau boueuse par décantation",
  "fichier": "sims/1AC/L13/simulation_E1AC-20.html"
 },
 {
  "id": "E1AC-21",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L13",
  "lecon_num": 13,
  "type": "paillasse",
  "titre": "La filtration",
  "titre_complet": "Paillasse virtuelle — E1AC-21 · La filtration",
  "fichier": "sims/1AC/L13/enhanced_simulation_E1AC-21.html"
 },
 {
  "id": "E1AC-21",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L13",
  "lecon_num": 13,
  "type": "simulation",
  "titre": "Rendre limpide une eau décantée par filtration",
  "titre_complet": "Simulation — Rendre limpide une eau décantée par filtration",
  "fichier": "sims/1AC/L13/simulation_E1AC-21.html"
 },
 {
  "id": "E1AC-25",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L14",
  "lecon_num": 14,
  "type": "paillasse",
  "titre": "Le palier d'ebullition",
  "titre_complet": "Paillasse virtuelle — E1AC-25 · Le palier d'ebullition",
  "fichier": "sims/1AC/L14/enhanced_simulation_E1AC-25.html"
 },
 {
  "id": "E1AC-25",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L14",
  "lecon_num": 14,
  "type": "simulation",
  "titre": "L'ébullition de l'eau distillée et celle de l'eau salée",
  "titre_complet": "Simulation — L'ébullition de l'eau distillée et celle de l'eau salée",
  "fichier": "sims/1AC/L14/simulation_E1AC-25.html"
 },
 {
  "id": "E1AC-26",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L15",
  "lecon_num": 15,
  "type": "paillasse",
  "titre": "Maquette de station",
  "titre_complet": "Paillasse virtuelle — E1AC-26 · Maquette de station",
  "fichier": "sims/1AC/L15/enhanced_simulation_E1AC-26.html"
 },
 {
  "id": "E1AC-26",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L15",
  "lecon_num": 15,
  "type": "simulation",
  "titre": "Maquette de station : rendre limpide l'eau boueuse d'un oued",
  "titre_complet": "Simulation — Maquette de station : rendre limpide l'eau boueuse d'un oued",
  "fichier": "sims/1AC/L15/simulation_E1AC-26.html"
 },
 {
  "id": "E1AC-27",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L17",
  "lecon_num": 17,
  "type": "paillasse",
  "titre": "Le circuit ferme et le circuit ouvert",
  "titre_complet": "Paillasse virtuelle — E1AC-27 · Le circuit ferme et le circuit ouvert",
  "fichier": "sims/1AC/L17/enhanced_simulation_E1AC-27.html"
 },
 {
  "id": "E1AC-27",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L17",
  "lecon_num": 17,
  "type": "simulation",
  "titre": "Réaliser un circuit électrique simple : circuit fermé, circuit ouvert",
  "titre_complet": "Simulation — Réaliser un circuit électrique simple : circuit fermé, circuit ouvert",
  "fichier": "sims/1AC/L17/simulation_E1AC-27.html"
 },
 {
  "id": "E1AC-28",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L17",
  "lecon_num": 17,
  "type": "paillasse",
  "titre": "Polarise ou symetrique",
  "titre_complet": "Paillasse virtuelle — E1AC-28 · Polarise ou symetrique",
  "fichier": "sims/1AC/L17/enhanced_simulation_E1AC-28.html"
 },
 {
  "id": "E1AC-28",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L17",
  "lecon_num": 17,
  "type": "simulation",
  "titre": "Retourner un dipôle : polarisé ou symétrique ?",
  "titre_complet": "Simulation — Retourner un dipôle : polarisé ou symétrique ?",
  "fichier": "sims/1AC/L17/simulation_E1AC-28.html"
 },
 {
  "id": "E1AC-29",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L17",
  "lecon_num": 17,
  "type": "paillasse",
  "titre": "Conducteurs et isolants",
  "titre_complet": "Paillasse virtuelle — E1AC-29 · Conducteurs et isolants",
  "fichier": "sims/1AC/L17/enhanced_simulation_E1AC-29.html"
 },
 {
  "id": "E1AC-29",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L17",
  "lecon_num": 17,
  "type": "simulation",
  "titre": "Conducteurs ou isolants : tester des matériaux à la lampe témoin",
  "titre_complet": "Simulation — Conducteurs ou isolants : tester des matériaux à la lampe témoin",
  "fichier": "sims/1AC/L17/simulation_E1AC-29.html"
 },
 {
  "id": "E1AC-30",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L18",
  "lecon_num": 18,
  "type": "paillasse",
  "titre": "Le montage en serie",
  "titre_complet": "Paillasse virtuelle — E1AC-30 · Le montage en serie",
  "fichier": "sims/1AC/L18/enhanced_simulation_E1AC-30.html"
 },
 {
  "id": "E1AC-30",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L18",
  "lecon_num": 18,
  "type": "simulation",
  "titre": "Le montage en série : deux lampes l'une à la suite de l'autre",
  "titre_complet": "Simulation — Le montage en série : deux lampes l'une à la suite de l'autre",
  "fichier": "sims/1AC/L18/simulation_E1AC-30.html"
 },
 {
  "id": "E1AC-31",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L18",
  "lecon_num": 18,
  "type": "paillasse",
  "titre": "Le montage en derivation",
  "titre_complet": "Paillasse virtuelle — E1AC-31 · Le montage en derivation",
  "fichier": "sims/1AC/L18/enhanced_simulation_E1AC-31.html"
 },
 {
  "id": "E1AC-31",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L18",
  "lecon_num": 18,
  "type": "simulation",
  "titre": "Le montage en dérivation : deux lampes côte à côte",
  "titre_complet": "Simulation — Le montage en dérivation : deux lampes côte à côte",
  "fichier": "sims/1AC/L18/simulation_E1AC-31.html"
 },
 {
  "id": "E1AC-32",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L19",
  "lecon_num": 19,
  "type": "paillasse",
  "titre": "Le sens du courant",
  "titre_complet": "Paillasse virtuelle — E1AC-32 · Le sens du courant",
  "fichier": "sims/1AC/L19/enhanced_simulation_E1AC-32.html"
 },
 {
  "id": "E1AC-32",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L19",
  "lecon_num": 19,
  "type": "simulation",
  "titre": "Le sens du courant : la diode et le moteur comme témoins",
  "titre_complet": "Simulation — Le sens du courant : la diode et le moteur comme témoins",
  "fichier": "sims/1AC/L19/simulation_E1AC-32.html"
 },
 {
  "id": "E1AC-33",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L19",
  "lecon_num": 19,
  "type": "paillasse",
  "titre": "L'amperemetre",
  "titre_complet": "Paillasse virtuelle — E1AC-33 · L'amperemetre",
  "fichier": "sims/1AC/L19/enhanced_simulation_E1AC-33.html"
 },
 {
  "id": "E1AC-33",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L19",
  "lecon_num": 19,
  "type": "simulation",
  "titre": "Mesurer l'intensité du courant avec un ampèremètre",
  "titre_complet": "Simulation — Mesurer l'intensité du courant avec un ampèremètre",
  "fichier": "sims/1AC/L19/simulation_E1AC-33.html"
 },
 {
  "id": "E1AC-34",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L19",
  "lecon_num": 19,
  "type": "paillasse",
  "titre": "Le voltmetre",
  "titre_complet": "Paillasse virtuelle — E1AC-34 · Le voltmetre",
  "fichier": "sims/1AC/L19/enhanced_simulation_E1AC-34.html"
 },
 {
  "id": "E1AC-34",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L19",
  "lecon_num": 19,
  "type": "simulation",
  "titre": "Mesurer la tension aux bornes d'un dipôle avec un voltmètre",
  "titre_complet": "Simulation — Mesurer la tension aux bornes d'un dipôle avec un voltmètre",
  "fichier": "sims/1AC/L19/simulation_E1AC-34.html"
 },
 {
  "id": "E1AC-35",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L20",
  "lecon_num": 20,
  "type": "paillasse",
  "titre": "L'ohmmetre et le code des couleurs",
  "titre_complet": "Paillasse virtuelle — E1AC-35 · L'ohmmetre et le code des couleurs",
  "fichier": "sims/1AC/L20/enhanced_simulation_E1AC-35.html"
 },
 {
  "id": "E1AC-35",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L20",
  "lecon_num": 20,
  "type": "simulation",
  "titre": "Déterminer la valeur d'un conducteur ohmique : l'ohmmètre et le code des couleurs",
  "titre_complet": "Simulation — Déterminer la valeur d'un conducteur ohmique : l'ohmmètre et le code des couleurs",
  "fichier": "sims/1AC/L20/simulation_E1AC-35.html"
 },
 {
  "id": "E1AC-36",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L20",
  "lecon_num": 20,
  "type": "paillasse",
  "titre": "La resistance freine le courant",
  "titre_complet": "Paillasse virtuelle — E1AC-36 · La resistance freine le courant",
  "fichier": "sims/1AC/L20/enhanced_simulation_E1AC-36.html"
 },
 {
  "id": "E1AC-36",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L20",
  "lecon_num": 20,
  "type": "simulation",
  "titre": "Influence de la résistance sur l'intensité du courant dans un circuit série",
  "titre_complet": "Simulation — Influence de la résistance sur l'intensité du courant dans un circuit série",
  "fichier": "sims/1AC/L20/simulation_E1AC-36.html"
 },
 {
  "id": "E1AC-37",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L21",
  "lecon_num": 21,
  "type": "paillasse",
  "titre": "La loi des noeuds",
  "titre_complet": "Paillasse virtuelle — E1AC-37 · La loi des noeuds",
  "fichier": "sims/1AC/L21/enhanced_simulation_E1AC-37.html"
 },
 {
  "id": "E1AC-37",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L21",
  "lecon_num": 21,
  "type": "simulation",
  "titre": "Vérifier la loi des nœuds dans un circuit en dérivation",
  "titre_complet": "Simulation — Vérifier la loi des nœuds dans un circuit en dérivation",
  "fichier": "sims/1AC/L21/simulation_E1AC-37.html"
 },
 {
  "id": "E1AC-38",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L21",
  "lecon_num": 21,
  "type": "paillasse",
  "titre": "L'additivite des tensions",
  "titre_complet": "Paillasse virtuelle — E1AC-38 · L'additivite des tensions",
  "fichier": "sims/1AC/L21/enhanced_simulation_E1AC-38.html"
 },
 {
  "id": "E1AC-38",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L21",
  "lecon_num": 21,
  "type": "simulation",
  "titre": "Vérifier la loi d'additivité des tensions dans un circuit en série",
  "titre_complet": "Simulation — Vérifier la loi d'additivité des tensions dans un circuit en série",
  "fichier": "sims/1AC/L21/simulation_E1AC-38.html"
 },
 {
  "id": "E1AC-39",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L21",
  "lecon_num": 21,
  "type": "paillasse",
  "titre": "L'egalite des tensions en derivation",
  "titre_complet": "Paillasse virtuelle — E1AC-39 · L'egalite des tensions en derivation",
  "fichier": "sims/1AC/L21/enhanced_simulation_E1AC-39.html"
 },
 {
  "id": "E1AC-39",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L21",
  "lecon_num": 21,
  "type": "simulation",
  "titre": "Vérifier l'égalité des tensions aux bornes de dipôles en dérivation",
  "titre_complet": "Simulation — Vérifier l'égalité des tensions aux bornes de dipôles en dérivation",
  "fichier": "sims/1AC/L21/simulation_E1AC-39.html"
 },
 {
  "id": "E1AC-40",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L22",
  "lecon_num": 22,
  "type": "paillasse",
  "titre": "La recherche de panne",
  "titre_complet": "Paillasse virtuelle — E1AC-40 · La recherche de panne",
  "fichier": "sims/1AC/L22/enhanced_simulation_E1AC-40.html"
 },
 {
  "id": "E1AC-40",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L22",
  "lecon_num": 22,
  "type": "simulation",
  "titre": "Rechercher une panne dans un circuit avec une lampe témoin",
  "titre_complet": "Simulation — Rechercher une panne dans un circuit avec une lampe témoin",
  "fichier": "sims/1AC/L22/simulation_E1AC-40.html"
 },
 {
  "id": "E1AC-41",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L22",
  "lecon_num": 22,
  "type": "paillasse",
  "titre": "Le court-circuit",
  "titre_complet": "Paillasse virtuelle — E1AC-41 · Le court-circuit",
  "fichier": "sims/1AC/L22/enhanced_simulation_E1AC-41.html"
 },
 {
  "id": "E1AC-41",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L22",
  "lecon_num": 22,
  "type": "simulation",
  "titre": "Le court-circuit d'un dipôle en série et en dérivation",
  "titre_complet": "Simulation — Le court-circuit d'un dipôle en série et en dérivation",
  "fichier": "sims/1AC/L22/simulation_E1AC-41.html"
 },
 {
  "id": "E1AC-42",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L22",
  "lecon_num": 22,
  "type": "paillasse",
  "titre": "Le fusible et la paille de fer",
  "titre_complet": "Paillasse virtuelle — E1AC-42 · Le fusible et la paille de fer",
  "fichier": "sims/1AC/L22/enhanced_simulation_E1AC-42.html"
 },
 {
  "id": "E1AC-42",
  "niveau": "1AC",
  "niveau_libelle": "1APIC",
  "lecon": "L22",
  "lecon_num": 22,
  "type": "simulation",
  "titre": "Le rôle protecteur du fusible — l'expérience de la paille de fer",
  "titre_complet": "Simulation — Le rôle protecteur du fusible — l'expérience de la paille de fer",
  "fichier": "sims/1AC/L22/simulation_E1AC-42.html"
 },
 {
  "id": "E2AC-01",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L01",
  "lecon_num": 1,
  "type": "paillasse",
  "titre": "Les mouvements verticaux de l'air",
  "titre_complet": "Paillasse virtuelle — E2AC-01 · Les mouvements verticaux de l'air",
  "fichier": "sims/2AC/L01/enhanced_simulation_E2AC-01.html"
 },
 {
  "id": "E2AC-01",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L01",
  "lecon_num": 1,
  "type": "simulation",
  "titre": "Les mouvements verticaux de l'air",
  "titre_complet": "Simulation — Les mouvements verticaux de l'air",
  "fichier": "sims/2AC/L01/simulation_E2AC-01.html"
 },
 {
  "id": "E2AC-02",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L01",
  "lecon_num": 1,
  "type": "paillasse",
  "titre": "Les mouvements horizontaux de l'air : comment nait le vent ?",
  "titre_complet": "Paillasse virtuelle — E2AC-02 · Les mouvements horizontaux de l'air : comment nait le vent ?",
  "fichier": "sims/2AC/L01/enhanced_simulation_E2AC-02.html"
 },
 {
  "id": "E2AC-02",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L01",
  "lecon_num": 1,
  "type": "simulation",
  "titre": "Les mouvements horizontaux de l'air — comment naît le vent ?",
  "titre_complet": "Simulation — Les mouvements horizontaux de l'air — comment naît le vent ?",
  "fichier": "sims/2AC/L01/simulation_E2AC-02.html"
 },
 {
  "id": "E2AC-03",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L02",
  "lecon_num": 2,
  "type": "paillasse",
  "titre": "L'air a-t-il une masse ?",
  "titre_complet": "Paillasse virtuelle — E2AC-03 · L'air a-t-il une masse ?",
  "fichier": "sims/2AC/L02/enhanced_simulation_E2AC-03.html"
 },
 {
  "id": "E2AC-03",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L02",
  "lecon_num": 2,
  "type": "simulation",
  "titre": "L'air a-t-il une masse ?",
  "titre_complet": "Simulation — L'air a-t-il une masse ?",
  "fichier": "sims/2AC/L02/simulation_E2AC-03.html"
 },
 {
  "id": "E2AC-04",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L02",
  "lecon_num": 2,
  "type": "paillasse",
  "titre": "Quelle est la composition de l'air ?",
  "titre_complet": "Paillasse virtuelle — E2AC-04 · Quelle est la composition de l'air ?",
  "fichier": "sims/2AC/L02/enhanced_simulation_E2AC-04.html"
 },
 {
  "id": "E2AC-04",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L02",
  "lecon_num": 2,
  "type": "simulation",
  "titre": "Quelle est la composition de l'air ?",
  "titre_complet": "Simulation — Quelle est la composition de l'air ?",
  "fichier": "sims/2AC/L02/simulation_E2AC-04.html"
 },
 {
  "id": "E2AC-05",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L03",
  "lecon_num": 3,
  "type": "paillasse",
  "titre": "Construire les modèles compacts de quelques molécules",
  "titre_complet": "Paillasse virtuelle — E2AC-05 · Construire les modèles compacts de quelques molécules",
  "fichier": "sims/2AC/L03/enhanced_simulation_E2AC-05.html"
 },
 {
  "id": "E2AC-05",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L03",
  "lecon_num": 3,
  "type": "simulation",
  "titre": "Construire les modèles compacts de quelques molécules",
  "titre_complet": "Simulation — Construire les modèles compacts de quelques molécules",
  "fichier": "sims/2AC/L03/simulation_E2AC-05.html"
 },
 {
  "id": "E2AC-06",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L04",
  "lecon_num": 4,
  "type": "paillasse",
  "titre": "La combustion du carbone",
  "titre_complet": "Paillasse virtuelle — E2AC-06 · La combustion du carbone",
  "fichier": "sims/2AC/L04/enhanced_simulation_E2AC-06.html"
 },
 {
  "id": "E2AC-06",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L04",
  "lecon_num": 4,
  "type": "simulation",
  "titre": "La combustion du carbone",
  "titre_complet": "Simulation — La combustion du carbone",
  "fichier": "sims/2AC/L04/simulation_E2AC-06.html"
 },
 {
  "id": "E2AC-07",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L04",
  "lecon_num": 4,
  "type": "paillasse",
  "titre": "La combustion du butane",
  "titre_complet": "Paillasse virtuelle — E2AC-07 · La combustion du butane",
  "fichier": "sims/2AC/L04/enhanced_simulation_E2AC-07.html"
 },
 {
  "id": "E2AC-07",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L04",
  "lecon_num": 4,
  "type": "simulation",
  "titre": "La combustion du butane : complète ou incomplète ?",
  "titre_complet": "Simulation — La combustion du butane : complète ou incomplète ?",
  "fichier": "sims/2AC/L04/simulation_E2AC-07.html"
 },
 {
  "id": "E2AC-08",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L04",
  "lecon_num": 4,
  "type": "paillasse",
  "titre": "La combustion d'une cigarette",
  "titre_complet": "Paillasse virtuelle — E2AC-08 · La combustion d'une cigarette",
  "fichier": "sims/2AC/L04/enhanced_simulation_E2AC-08.html"
 },
 {
  "id": "E2AC-08",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L04",
  "lecon_num": 4,
  "type": "simulation",
  "titre": "La combustion d'une cigarette",
  "titre_complet": "Simulation — La combustion d'une cigarette",
  "fichier": "sims/2AC/L04/simulation_E2AC-08.html"
 },
 {
  "id": "E2AC-09",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L05",
  "lecon_num": 5,
  "type": "paillasse",
  "titre": "Le fer et le soufre",
  "titre_complet": "Paillasse virtuelle — E2AC-09 · Le fer et le soufre",
  "fichier": "sims/2AC/L05/enhanced_simulation_E2AC-09.html"
 },
 {
  "id": "E2AC-09",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L05",
  "lecon_num": 5,
  "type": "simulation",
  "titre": "Le fer réagit-il avec le soufre ?",
  "titre_complet": "Simulation — Le fer réagit-il avec le soufre ?",
  "fichier": "sims/2AC/L05/simulation_E2AC-09.html"
 },
 {
  "id": "E2AC-10",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L05",
  "lecon_num": 5,
  "type": "paillasse",
  "titre": "Le fer dans le dioxygène",
  "titre_complet": "Paillasse virtuelle — E2AC-10 · Le fer dans le dioxygène",
  "fichier": "sims/2AC/L05/enhanced_simulation_E2AC-10.html"
 },
 {
  "id": "E2AC-10",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L05",
  "lecon_num": 5,
  "type": "simulation",
  "titre": "Le fer brûle-t-il dans le dioxygène ?",
  "titre_complet": "Simulation — Le fer brûle-t-il dans le dioxygène ?",
  "fichier": "sims/2AC/L05/simulation_E2AC-10.html"
 },
 {
  "id": "E2AC-11",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L06",
  "lecon_num": 6,
  "type": "paillasse",
  "titre": "La masse se conserve-t-elle ?",
  "titre_complet": "Paillasse virtuelle — E2AC-11 · La masse se conserve-t-elle ?",
  "fichier": "sims/2AC/L06/enhanced_simulation_E2AC-11.html"
 },
 {
  "id": "E2AC-11",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L06",
  "lecon_num": 6,
  "type": "simulation",
  "titre": "La masse se conserve-t-elle au cours d'une réaction chimique ?",
  "titre_complet": "Simulation — La masse se conserve-t-elle au cours d'une réaction chimique ?",
  "fichier": "sims/2AC/L06/simulation_E2AC-11.html"
 },
 {
  "id": "E2AC-12",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L06",
  "lecon_num": 6,
  "type": "paillasse",
  "titre": "Que deviennent les atomes ?",
  "titre_complet": "Paillasse virtuelle — E2AC-12 · Que deviennent les atomes ?",
  "fichier": "sims/2AC/L06/enhanced_simulation_E2AC-12.html"
 },
 {
  "id": "E2AC-12",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L06",
  "lecon_num": 6,
  "type": "simulation",
  "titre": "Que deviennent les atomes au cours d'une réaction chimique ?",
  "titre_complet": "Simulation — Que deviennent les atomes au cours d'une réaction chimique ?",
  "fichier": "sims/2AC/L06/simulation_E2AC-12.html"
 },
 {
  "id": "E2AC-14",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L07",
  "lecon_num": 7,
  "type": "paillasse",
  "titre": "Fabriquer une matiere naturelle : la preparation du dioxygene",
  "titre_complet": "Paillasse virtuelle — E2AC-14 · Fabriquer une matiere naturelle : la preparation du dioxygene",
  "fichier": "sims/2AC/L07/enhanced_simulation_E2AC-14.html"
 },
 {
  "id": "E2AC-14",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L07",
  "lecon_num": 7,
  "type": "simulation",
  "titre": "Fabriquer une matière naturelle : la préparation du dioxygène",
  "titre_complet": "Simulation — Fabriquer une matière naturelle : la préparation du dioxygène",
  "fichier": "sims/2AC/L07/simulation_E2AC-14.html"
 },
 {
  "id": "E2AC-15",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L08",
  "lecon_num": 8,
  "type": "paillasse",
  "titre": "Simuler l'effet de serre : deux bocaux, deux gaz, une seule lampe",
  "titre_complet": "Paillasse virtuelle — E2AC-15 · Simuler l'effet de serre : deux bocaux, deux gaz, une seule lampe",
  "fichier": "sims/2AC/L08/enhanced_simulation_E2AC-15.html"
 },
 {
  "id": "E2AC-15",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L08",
  "lecon_num": 8,
  "type": "simulation",
  "titre": "Simuler l'effet de serre : deux bocaux, deux gaz, une seule lampe",
  "titre_complet": "Simulation — Simuler l'effet de serre : deux bocaux, deux gaz, une seule lampe",
  "fichier": "sims/2AC/L08/simulation_E2AC-15.html"
 },
 {
  "id": "E2AC-16",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L10",
  "lecon_num": 10,
  "type": "paillasse",
  "titre": "Source primaire ou source secondaire ? le test de l'obscurité",
  "titre_complet": "Paillasse virtuelle — E2AC-16 · Source primaire ou source secondaire ? le test de l'obscurité",
  "fichier": "sims/2AC/L10/enhanced_simulation_E2AC-16.html"
 },
 {
  "id": "E2AC-16",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L10",
  "lecon_num": 10,
  "type": "simulation",
  "titre": "Source primaire ou source secondaire ? le test de l'obscurité",
  "titre_complet": "Simulation — Source primaire ou source secondaire ? le test de l'obscurité",
  "fichier": "sims/2AC/L10/simulation_E2AC-16.html"
 },
 {
  "id": "E2AC-17",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L11",
  "lecon_num": 11,
  "type": "paillasse",
  "titre": "La dispersion de la lumière blanche par un prisme",
  "titre_complet": "Paillasse virtuelle — E2AC-17 · La dispersion de la lumière blanche par un prisme",
  "fichier": "sims/2AC/L11/enhanced_simulation_E2AC-17.html"
 },
 {
  "id": "E2AC-17",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L11",
  "lecon_num": 11,
  "type": "simulation",
  "titre": "La dispersion de la lumière blanche par un prisme",
  "titre_complet": "Simulation — La dispersion de la lumière blanche par un prisme",
  "fichier": "sims/2AC/L11/simulation_E2AC-17.html"
 },
 {
  "id": "E2AC-18",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L11",
  "lecon_num": 11,
  "type": "paillasse",
  "titre": "La recomposition de la lumière blanche — le disque de Newton",
  "titre_complet": "Paillasse virtuelle — E2AC-18 · La recomposition de la lumière blanche — le disque de Newton",
  "fichier": "sims/2AC/L11/enhanced_simulation_E2AC-18.html"
 },
 {
  "id": "E2AC-18",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L11",
  "lecon_num": 11,
  "type": "simulation",
  "titre": "La recomposition de la lumière blanche — le disque de Newton",
  "titre_complet": "Simulation — La recomposition de la lumière blanche — le disque de Newton",
  "fichier": "sims/2AC/L11/simulation_E2AC-18.html"
 },
 {
  "id": "E2AC-19",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L12",
  "lecon_num": 12,
  "type": "paillasse",
  "titre": "Classer les milieux de propagation de la lumière",
  "titre_complet": "Paillasse virtuelle — E2AC-19 · Classer les milieux de propagation de la lumière",
  "fichier": "sims/2AC/L12/enhanced_simulation_E2AC-19.html"
 },
 {
  "id": "E2AC-19",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L12",
  "lecon_num": 12,
  "type": "simulation",
  "titre": "Classer les milieux de propagation de la lumière",
  "titre_complet": "Simulation — Classer les milieux de propagation de la lumière",
  "fichier": "sims/2AC/L12/simulation_E2AC-19.html"
 },
 {
  "id": "E2AC-20",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L12",
  "lecon_num": 12,
  "type": "paillasse",
  "titre": "Vérifier la propagation rectiligne de la lumière",
  "titre_complet": "Paillasse virtuelle — E2AC-20 · Vérifier la propagation rectiligne de la lumière",
  "fichier": "sims/2AC/L12/enhanced_simulation_E2AC-20.html"
 },
 {
  "id": "E2AC-20",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L12",
  "lecon_num": 12,
  "type": "simulation",
  "titre": "Vérifier la propagation rectiligne de la lumière",
  "titre_complet": "Simulation — Vérifier la propagation rectiligne de la lumière",
  "fichier": "sims/2AC/L12/simulation_E2AC-20.html"
 },
 {
  "id": "E2AC-21",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L13",
  "lecon_num": 13,
  "type": "paillasse",
  "titre": "La chambre noire : l'image d'un objet lumineux",
  "titre_complet": "Paillasse virtuelle — E2AC-21 · La chambre noire : l'image d'un objet lumineux",
  "fichier": "sims/2AC/L13/enhanced_simulation_E2AC-21.html"
 },
 {
  "id": "E2AC-21",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L13",
  "lecon_num": 13,
  "type": "simulation",
  "titre": "La chambre noire : l'image d'un objet lumineux",
  "titre_complet": "Simulation — La chambre noire : l'image d'un objet lumineux",
  "fichier": "sims/2AC/L13/simulation_E2AC-21.html"
 },
 {
  "id": "E2AC-22",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L13",
  "lecon_num": 13,
  "type": "paillasse",
  "titre": "Les ombres : source ponctuelle, puis source étendue",
  "titre_complet": "Paillasse virtuelle — E2AC-22 · Les ombres : source ponctuelle, puis source étendue",
  "fichier": "sims/2AC/L13/enhanced_simulation_E2AC-22.html"
 },
 {
  "id": "E2AC-22",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L13",
  "lecon_num": 13,
  "type": "simulation",
  "titre": "Les ombres : source ponctuelle, puis source étendue",
  "titre_complet": "Simulation — Les ombres : source ponctuelle, puis source étendue",
  "fichier": "sims/2AC/L13/simulation_E2AC-22.html"
 },
 {
  "id": "E2AC-23",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L14",
  "lecon_num": 14,
  "type": "paillasse",
  "titre": "Classer les lentilles minces",
  "titre_complet": "Paillasse virtuelle — E2AC-23 · Classer les lentilles minces",
  "fichier": "sims/2AC/L14/enhanced_simulation_E2AC-23.html"
 },
 {
  "id": "E2AC-23",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L14",
  "lecon_num": 14,
  "type": "simulation",
  "titre": "Classer les lentilles minces : convergentes ou divergentes",
  "titre_complet": "Simulation — Classer les lentilles minces : convergentes ou divergentes",
  "fichier": "sims/2AC/L14/simulation_E2AC-23.html"
 },
 {
  "id": "E2AC-24",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L14",
  "lecon_num": 14,
  "type": "paillasse",
  "titre": "Déterminer une distance focale et comparer les vergences",
  "titre_complet": "Paillasse virtuelle — E2AC-24 · Déterminer une distance focale et comparer les vergences",
  "fichier": "sims/2AC/L14/enhanced_simulation_E2AC-24.html"
 },
 {
  "id": "E2AC-24",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L14",
  "lecon_num": 14,
  "type": "simulation",
  "titre": "Déterminer une distance focale et comparer les vergences de deux lentilles",
  "titre_complet": "Simulation — Déterminer une distance focale et comparer les vergences de deux lentilles",
  "fichier": "sims/2AC/L14/simulation_E2AC-24.html"
 },
 {
  "id": "E2AC-25",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L14",
  "lecon_num": 14,
  "type": "paillasse",
  "titre": "L'image d'un objet lumineux donnee par une lentille convergente",
  "titre_complet": "Paillasse virtuelle — E2AC-25 · L'image d'un objet lumineux donnee par une lentille convergente",
  "fichier": "sims/2AC/L14/enhanced_simulation_E2AC-25.html"
 },
 {
  "id": "E2AC-25",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L14",
  "lecon_num": 14,
  "type": "simulation",
  "titre": "L'image d'un objet lumineux donnée par une lentille convergente",
  "titre_complet": "Simulation — L'image d'un objet lumineux donnée par une lentille convergente",
  "fichier": "sims/2AC/L14/simulation_E2AC-25.html"
 },
 {
  "id": "E2AC-26",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L15",
  "lecon_num": 15,
  "type": "paillasse",
  "titre": "Le principe de la loupe : l'objet entre le foyer et la lentille",
  "titre_complet": "Paillasse virtuelle — E2AC-26 · Le principe de la loupe : l'objet entre le foyer et la lentille",
  "fichier": "sims/2AC/L15/enhanced_simulation_E2AC-26.html"
 },
 {
  "id": "E2AC-26",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L15",
  "lecon_num": 15,
  "type": "simulation",
  "titre": "Le principe de la loupe : l'objet entre le foyer et la lentille",
  "titre_complet": "Simulation — Le principe de la loupe : l'objet entre le foyer et la lentille",
  "fichier": "sims/2AC/L15/simulation_E2AC-26.html"
 },
 {
  "id": "E2AC-27",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L15",
  "lecon_num": 15,
  "type": "paillasse",
  "titre": "L'œil réduit : image nette, défauts de la vision et correction",
  "titre_complet": "Paillasse virtuelle — E2AC-27 · L'œil réduit : image nette, défauts de la vision et correction",
  "fichier": "sims/2AC/L15/enhanced_simulation_E2AC-27.html"
 },
 {
  "id": "E2AC-27",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L15",
  "lecon_num": 15,
  "type": "simulation",
  "titre": "L'œil réduit : image nette, défauts de la vision et correction",
  "titre_complet": "Simulation — L'œil réduit : image nette, défauts de la vision et correction",
  "fichier": "sims/2AC/L15/simulation_E2AC-27.html"
 },
 {
  "id": "E2AC-28",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L16",
  "lecon_num": 16,
  "type": "paillasse",
  "titre": "Que voit-on à l'oscilloscope : une pile, puis un générateur alternatif ?",
  "titre_complet": "Paillasse virtuelle — E2AC-28 · Que voit-on à l'oscilloscope : une pile, puis un générateur alternatif ?",
  "fichier": "sims/2AC/L16/enhanced_simulation_E2AC-28.html"
 },
 {
  "id": "E2AC-28",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L16",
  "lecon_num": 16,
  "type": "simulation",
  "titre": "Que voit-on à l'oscilloscope : une pile, puis un générateur alternatif ?",
  "titre_complet": "Simulation — Que voit-on à l'oscilloscope : une pile, puis un générateur alternatif ?",
  "fichier": "sims/2AC/L16/simulation_E2AC-28.html"
 },
 {
  "id": "E2AC-29",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L16",
  "lecon_num": 16,
  "type": "paillasse",
  "titre": "Que lit-on sur un oscillogramme ?",
  "titre_complet": "Paillasse virtuelle — E2AC-29 · Que lit-on sur un oscillogramme ?",
  "fichier": "sims/2AC/L16/enhanced_simulation_E2AC-29.html"
 },
 {
  "id": "E2AC-29",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L16",
  "lecon_num": 16,
  "type": "simulation",
  "titre": "Que peut-on lire sur un oscillogramme ?",
  "titre_complet": "Simulation — Que peut-on lire sur un oscillogramme ?",
  "fichier": "sims/2AC/L16/simulation_E2AC-29.html"
 },
 {
  "id": "E2AC-30",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L16",
  "lecon_num": 16,
  "type": "paillasse",
  "titre": "La valeur efficace",
  "titre_complet": "Paillasse virtuelle — E2AC-30 · La valeur efficace",
  "fichier": "sims/2AC/L16/enhanced_simulation_E2AC-30.html"
 },
 {
  "id": "E2AC-30",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L16",
  "lecon_num": 16,
  "type": "simulation",
  "titre": "Pourquoi le voltmètre n'affiche-t-il pas la valeur maximale ?",
  "titre_complet": "Simulation — Pourquoi le voltmètre n'affiche-t-il pas la valeur maximale ?",
  "fichier": "sims/2AC/L16/simulation_E2AC-30.html"
 },
 {
  "id": "E2AC-31",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L17",
  "lecon_num": 17,
  "type": "paillasse",
  "titre": "Les trois fils d'une prise",
  "titre_complet": "Paillasse virtuelle — E2AC-31 · Les trois fils d'une prise",
  "fichier": "sims/2AC/L17/enhanced_simulation_E2AC-31.html"
 },
 {
  "id": "E2AC-31",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L17",
  "lecon_num": 17,
  "type": "simulation",
  "titre": "Les trois fils d'une prise se ressemblent : comment les distinguer ?",
  "titre_complet": "Simulation — Les trois fils d'une prise se ressemblent : comment les distinguer ?",
  "fichier": "sims/2AC/L17/simulation_E2AC-31.html"
 },
 {
  "id": "E2AC-32",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L17",
  "lecon_num": 17,
  "type": "paillasse",
  "titre": "Les tensions d'une prise",
  "titre_complet": "Paillasse virtuelle — E2AC-32 · Les tensions d'une prise",
  "fichier": "sims/2AC/L17/enhanced_simulation_E2AC-32.html"
 },
 {
  "id": "E2AC-32",
  "niveau": "2AC",
  "niveau_libelle": "2APIC",
  "lecon": "L17",
  "lecon_num": 17,
  "type": "simulation",
  "titre": "Quelles tensions existent entre les trois fils d'une prise ?",
  "titre_complet": "Simulation — Quelles tensions existent entre les trois fils d'une prise ?",
  "fichier": "sims/2AC/L17/simulation_E2AC-32.html"
 },
 {
  "id": "E3AC-02",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L03",
  "lecon_num": 3,
  "type": "paillasse",
  "titre": "Les facteurs de la rouille",
  "titre_complet": "Paillasse virtuelle — E3AC-02 · Les facteurs de la rouille",
  "fichier": "sims/3AC/L03/enhanced_simulation_E3AC-02.html"
 },
 {
  "id": "E3AC-03",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L03",
  "lecon_num": 3,
  "type": "paillasse",
  "titre": "La couche d'alumine",
  "titre_complet": "Paillasse virtuelle — E3AC-03 · La couche d'alumine",
  "fichier": "sims/3AC/L03/enhanced_simulation_E3AC-03.html"
 },
 {
  "id": "E3AC-04",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L03",
  "lecon_num": 3,
  "type": "paillasse",
  "titre": "Les produits de la combustion",
  "titre_complet": "Paillasse virtuelle — E3AC-04 · Les produits de la combustion",
  "fichier": "sims/3AC/L03/enhanced_simulation_E3AC-04.html"
 },
 {
  "id": "E3AC-05",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L04",
  "lecon_num": 4,
  "type": "paillasse",
  "titre": "Mesurer le pH et classer les solutions",
  "titre_complet": "Paillasse virtuelle — E3AC-05 · Mesurer le pH et classer les solutions",
  "fichier": "sims/3AC/L04/enhanced_simulation_E3AC-05.html"
 },
 {
  "id": "E3AC-06",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L05",
  "lecon_num": 5,
  "type": "paillasse",
  "titre": "La solution d'acide chlorhydrique attaque-t-elle tous les métaux ?",
  "titre_complet": "Paillasse virtuelle — E3AC-06 · La solution d'acide chlorhydrique attaque-t-elle tous les métaux ?",
  "fichier": "sims/3AC/L05/enhanced_simulation_E3AC-06.html"
 },
 {
  "id": "E3AC-07",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L06",
  "lecon_num": 6,
  "type": "paillasse",
  "titre": "La reconnaissance des ions métalliques par la soude",
  "titre_complet": "Paillasse virtuelle — E3AC-07 · La reconnaissance des ions métalliques par la soude",
  "fichier": "sims/3AC/L06/enhanced_simulation_E3AC-07.html"
 },
 {
  "id": "E3AC-08",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L06",
  "lecon_num": 6,
  "type": "paillasse",
  "titre": "La reconnaissance des ions chlorure par le nitrate d'argent",
  "titre_complet": "Paillasse virtuelle — E3AC-08 · La reconnaissance des ions chlorure par le nitrate d'argent",
  "fichier": "sims/3AC/L06/enhanced_simulation_E3AC-08.html"
 },
 {
  "id": "E3AC-09",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L06",
  "lecon_num": 6,
  "type": "paillasse",
  "titre": "L'identification des ions d'une solution inconnue",
  "titre_complet": "Paillasse virtuelle — E3AC-09 · L'identification des ions d'une solution inconnue",
  "fichier": "sims/3AC/L06/enhanced_simulation_E3AC-09.html"
 },
 {
  "id": "E3AC-10",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L07",
  "lecon_num": 7,
  "type": "paillasse",
  "titre": "Biodégradable ou non ? Le devenir de six déchets enfouis",
  "titre_complet": "Paillasse virtuelle — E3AC-10 · Biodégradable ou non ? Le devenir de six déchets enfouis",
  "fichier": "sims/3AC/L07/enhanced_simulation_E3AC-10.html"
 },
 {
  "id": "E3AC-11",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L08",
  "lecon_num": 8,
  "type": "paillasse",
  "titre": "Le chariot, les deux figurines et l'élève qui marche",
  "titre_complet": "Paillasse virtuelle — E3AC-11 · Le chariot, les deux figurines et l'élève qui marche",
  "fichier": "sims/3AC/L08/enhanced_simulation_E3AC-11.html"
 },
 {
  "id": "E3AC-12",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L08",
  "lecon_num": 8,
  "type": "paillasse",
  "titre": "La valve de la roue : la trajectoire dépend du référentiel",
  "titre_complet": "Paillasse virtuelle — E3AC-12 · La valve de la roue : la trajectoire dépend du référentiel",
  "fichier": "sims/3AC/L08/enhanced_simulation_E3AC-12.html"
 },
 {
  "id": "E3AC-12",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L08",
  "lecon_num": 8,
  "type": "simulation",
  "titre": "La valve de la roue : matérialiser une trajectoire et montrer qu'elle dépend du référentiel",
  "titre_complet": "Simulation — La valve de la roue : matérialiser une trajectoire et montrer qu'elle dépend du référentiel",
  "fichier": "sims/3AC/L08/simulation_E3AC-12.html"
 },
 {
  "id": "E3AC-13",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L08",
  "lecon_num": 8,
  "type": "paillasse",
  "titre": "Une bille, trois portions de piste",
  "titre_complet": "Paillasse virtuelle — E3AC-13 · Une bille, trois portions de piste",
  "fichier": "sims/3AC/L08/enhanced_simulation_E3AC-13.html"
 },
 {
  "id": "E3AC-13",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L08",
  "lecon_num": 8,
  "type": "simulation",
  "titre": "Une bille, trois portions de piste : reconnaître un mouvement uniforme, accéléré et retardé",
  "titre_complet": "Simulation — Une bille, trois portions de piste : reconnaître un mouvement uniforme, accéléré et retardé",
  "fichier": "sims/3AC/L08/simulation_E3AC-13.html"
 },
 {
  "id": "E3AC-14",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L09",
  "lecon_num": 9,
  "type": "paillasse",
  "titre": "Notion d'action mécanique et ses effets",
  "titre_complet": "Paillasse virtuelle — E3AC-14 · Notion d'action mécanique et ses effets",
  "fichier": "sims/3AC/L09/enhanced_simulation_E3AC-14.html"
 },
 {
  "id": "E3AC-15",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L10",
  "lecon_num": 10,
  "type": "paillasse",
  "titre": "Peut-on mesurer une force avec un nombre ? Le dynamomètre",
  "titre_complet": "Paillasse virtuelle — E3AC-15 · Peut-on mesurer une force avec un nombre ? Le dynamomètre",
  "fichier": "sims/3AC/L10/enhanced_simulation_E3AC-15.html"
 },
 {
  "id": "E3AC-15",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L10",
  "lecon_num": 10,
  "type": "simulation",
  "titre": "Peut-on mesurer une force avec un nombre ? Le dynamomètre",
  "titre_complet": "Simulation — Peut-on mesurer une force avec un nombre ? Le dynamomètre",
  "fichier": "sims/3AC/L10/simulation_E3AC-15.html"
 },
 {
  "id": "E3AC-16",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L11",
  "lecon_num": 11,
  "type": "paillasse",
  "titre": "Que faut-il à deux forces pour qu'un solide reste immobile ?",
  "titre_complet": "Paillasse virtuelle — E3AC-16 · Que faut-il à deux forces pour qu'un solide reste immobile ?",
  "fichier": "sims/3AC/L11/enhanced_simulation_E3AC-16.html"
 },
 {
  "id": "E3AC-17",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L12",
  "lecon_num": 12,
  "type": "paillasse",
  "titre": "Le peson du marchand et la balance du marchand",
  "titre_complet": "Paillasse virtuelle — E3AC-17 · Le peson du marchand et la balance du marchand",
  "fichier": "sims/3AC/L12/enhanced_simulation_E3AC-17.html"
 },
 {
  "id": "E3AC-17",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L12",
  "lecon_num": 12,
  "type": "simulation",
  "titre": "Le peson du marchand et la balance du marchand : la relation entre le poids et la masse",
  "titre_complet": "Simulation — Le peson du marchand et la balance du marchand : la relation entre le poids et la masse",
  "fichier": "sims/3AC/L12/simulation_E3AC-17.html"
 },
 {
  "id": "E3AC-18",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L13",
  "lecon_num": 13,
  "type": "paillasse",
  "titre": "Vérification expérimentale de la loi d'Ohm",
  "titre_complet": "Paillasse virtuelle — E3AC-18 · Vérification expérimentale de la loi d'Ohm",
  "fichier": "sims/3AC/L13/enhanced_simulation_E3AC-18.html"
 },
 {
  "id": "E3AC-18",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L13",
  "lecon_num": 13,
  "type": "simulation",
  "titre": "Vérification expérimentale de la loi d'Ohm",
  "titre_complet": "Simulation — Vérification expérimentale de la loi d'Ohm",
  "fichier": "sims/3AC/L13/simulation_E3AC-18.html"
 },
 {
  "id": "E3AC-19",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L14",
  "lecon_num": 14,
  "type": "paillasse",
  "titre": "D'où vient le nombre écrit en watts ?",
  "titre_complet": "Paillasse virtuelle — E3AC-19 · D'où vient le nombre écrit en watts ?",
  "fichier": "sims/3AC/L14/enhanced_simulation_E3AC-19.html"
 },
 {
  "id": "E3AC-19",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L14",
  "lecon_num": 14,
  "type": "simulation",
  "titre": "D'où vient le nombre écrit en watts sur un appareil électrique ?",
  "titre_complet": "Simulation — D'où vient le nombre écrit en watts sur un appareil électrique ?",
  "fichier": "sims/3AC/L14/simulation_E3AC-19.html"
 },
 {
  "id": "E3AC-20",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L14",
  "lecon_num": 14,
  "type": "paillasse",
  "titre": "La tension nominale d'un appareil",
  "titre_complet": "Paillasse virtuelle — E3AC-20 · La tension nominale d'un appareil",
  "fichier": "sims/3AC/L14/enhanced_simulation_E3AC-20.html"
 },
 {
  "id": "E3AC-21",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L15",
  "lecon_num": 15,
  "type": "paillasse",
  "titre": "De quoi dépend l'énergie qu'un appareil consomme ?",
  "titre_complet": "Paillasse virtuelle — E3AC-21 · De quoi dépend l'énergie qu'un appareil consomme ?",
  "fichier": "sims/3AC/L15/enhanced_simulation_E3AC-21.html"
 },
 {
  "id": "E3AC-21",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L15",
  "lecon_num": 15,
  "type": "simulation",
  "titre": "De quoi dépend l'énergie qu'un appareil consomme : de sa puissance, de la durée, ou des deux ?",
  "titre_complet": "Simulation — De quoi dépend l'énergie qu'un appareil consomme : de sa puissance, de la durée, ou des deux ?",
  "fichier": "sims/3AC/L15/simulation_E3AC-21.html"
 },
 {
  "id": "E3AC-22",
  "niveau": "3AC",
  "niveau_libelle": "3APIC",
  "lecon": "L15",
  "lecon_num": 15,
  "type": "paillasse",
  "titre": "Que compte le compteur de la maison ?",
  "titre_complet": "Paillasse virtuelle — E3AC-22 · Que compte le compteur de la maison ?",
  "fichier": "sims/3AC/L15/enhanced_simulation_E3AC-22.html"
 }
];
